name: Eliot McIntire
markdown: redcarpet
pygments: true

domain: predictiveecology.org
author: Eliot McIntire
email: eliot.mcintire@canada.ca

exclude: ["ReadMe.md", "Rakefile", "License.md"]

google_analytics:
   account: UA-58633549-1

github:
   username: PredictiveEcology

