---
title: "NetLogoR Dictionary"
author: "Sarah Bauduin"
date: "23 mars 2016"
output: html_document
---

This document is based on the [NetLogo Dictionary](https://ccl.northwestern.edu/netlogo/docs/dictionary.html). It lists all the entries in the NetLogo Dictionary, in an alphabetical order, and informs the best replacement(s) to use for building or translating a NetLogo model into R. Functions available in the NetLogoR package are listed, as well as functions from the R software and other packages when no NetLogoR equivalents were necessary to be built.

For the inverse dictionary, to find the NetLogo equivalents of the NetLogoR functions, please look at the NetLogoR documentation as the link to the equivalent(s) NetLogo entry is provided in the "See Also" section of each NetLogoR function.




* all?: NLall() in NetLogoR

* any?: NLany() in NetLogoR

* back (bk): bk() in NetLogoR

* can-move?: canMove() in NetLogoR

* clear-patches (cp): clearPatches() in NetLogoR

* clear-turtles (ct): clearTurtles() in NetLogoR

* count: count() in NetLogoR

* create-ordered-turtles (cro): createOTurtles() in NetLogoR
* create-ordered\<breeds>: createOTurtles() in NetLogoR

* create-turtles (crt): createTurtles() in NetLogoR
* create-\<breeds>: createTurtles() in NetLogoR

* die: die() in NetLogoR

* diffuse: diffuse() in NetLogoR

* diffuse4: diffuse() in NetLogoR

* distance: NLdist() in NetLogoR

* distancexy: NLdist() in NetLogoR

* downhill: downhill() in NetLogoR
* downhill4: downhill() in NetLogoR

* dx: dx() in NetLogoR
* dy: dy() in NetLogoR

* face: face() in NetLogoR

* facexy: face() in NetLogoR

* forward (fd): fd() in NetLogoR

* hatch: hatch() in NetLogoR
* hatch-\<breeds>: hatch() in NetLogoR

* home: home() in NetLogoR

* in-cone: inCone() in NetLogoR

* in-radius: inRadius() in NetLogoR

* inspect: inspect() in NetLogoR to inspect turtles. To inspect patches, use world[pxcor, pycor] to display patch variables values for the requested patches with coordinates [pxcor, pycor].

* is-agent?: isNLclass() in NetLogoR
* is-agentset?: isNLclass() in NetLogoR
* is-patch?: isNLclass() in NetLogoR. See also pExist() in NetLogoR.
* is-patch-set?: isNLclass() in NetLogoR. See also pExist() in NetLogoR.
* is-turtle?: isNLclass() in NetLogoR. See also tExist() in NetLogoR.
* is-turtle-set?: isNLclass() in NetLogoR. See also tExist() in NetLogoR.

* jump: fd() or bk() in NetLogoR (depending if jumping forward or backward)

* layout-circle: layoutCircle() in NetLogoR

* left (lt): left() in NetLogoR

* max-n-of: maxNof() in NetLogoR

* max-one-of: maxOneOf() in NetLogoR

* max-pxcor: maxPxcor() in NetLogoR
* max-pycor: maxPycor() in NetLogoR

* min-n-of: minNof() in NetLogoR

* min-one-of: minOneOf() in NetLogoR

* min-pxcor: minPxcor() in NetLogoR
* min-pycor: minPycor() in NetLogoR

* move-to: moveTo() in NetLogoR

* n-of: nOf() in NetLogoR

* neighbors: neighbors() in NetLogoR
* neighbors4: neighbors() in NetLogoR

* no-patches: noPatches() in NetLogoR

* no-turtles: noTurtles() in NetLogoR

* of: of() in NetLogoR. To return the variable value for one patch, world[pxcor, pycor] is faster; to return the variable value for multiple patches, use of().

* one-of: oneOf() in NetLogoR

* other: other() in NetLogoR

* patch: patch() in NetLogoR

* patch-ahead: patchAhead() in NetLogoR

* patch-at: patchAt() in NetLogoR

* patch-at-heading-and-distance: patchDistDir() in NetLogoR

* patch-here: patchHere() in NetLogoR

* patch-left-and-ahead: patchLeft() in NetLogoR
* patch-right-and-ahead: patchRight() in NetLogoR

* patch-set: patchSet() in NetLogoR

* patches: patches() in NetLogoR

* random-pxcor: randomPxcor() in NetLogoR
* random-pycor: randomPycor() in NetLogoR

* random-xcor: randomXcor() in NetLogoR
* random-ycor: randomYcor() in NetLogoR

* resize-world: resizeNLworld() in NetLogoR

* right (rt): right() in NetLogoR

* set: set() in NetLogoR

* sort-on: sortOn() in NetLogoR

* subtract-headings: subHeadings() in NetLogoR

* turtle: turtle() in NetLogoR

* turtles-at: turtlesAt() in NetLogoR

* turtles-on: turtlesOn() in NetLogoR
* \<breeds>-on: turtlesOn() in NetLogoR

* turtles-own: turtlesOwn() in NetLogoR
* \<breeds>-own: turtlesOwn() in NetLogoR

* turtle-set: turtleSet() in NetLogoR

* setxy: setXY() in NetLogoR

* sprout: sprout() in NetLogoR
* sprout-\<breeds>: sprout() in NetLogoR

* towards: towards() in NetLogoR

* towardsxy: towards() in NetLogoR

* uphill: uphill() in NetLogoR
* uphill4: uphill() in NetLogoR

* with: NLwith() in NetLogoR

* with-max: withMax() in NetLogoR

* with-min: withMin() in NetLogoR

* world-width: worldWidth() in NetLogoR
* world-height: worldHeight() in NetLogoR
